name: Test Accessibility Comment

on:
  pull_request:
    branches: [ main ]

jobs:
  test-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test PR Comment
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '## Test: Accessibility workflow is working!\\n✅ Using PAT for permissions\\n✅ Can post comments to PR'
            })
