name: Playwright E2E + Axe

on:
  push:
    branches: [ ci/run-e2e, main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium]
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Start app (background)
        run: |
          npm run build
          npm run start &
          # wait for the server
          npx wait-on http://localhost:3000

      - name: Run Playwright tests
        env:
          BASE_URL: http://localhost:3000
          TEST_PARENT_EMAIL: ${{ secrets.TEST_PARENT_EMAIL }}
          TEST_PARENT_PASSWORD: ${{ secrets.TEST_PARENT_PASSWORD }}
        run: |
          npx playwright test --project=chromium --reporter=list

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/

      - name: Upload axe artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: axe-results
          path: test-results/
